CMDB/CMDB/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from CMDB_Server import  views
import settings

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', views.main),
    url(r'^accounts/login/', views.acclogin, name='login'),
    url(r'^accounts/logout/', views.acclogout, name='logout'),
    url(r'^cmdb/', include('CMDB_Server.urls')),
    url(r'^recv_data/', views.recvdata),
    url(r'^accounts/', views.createuser,name='createuser'),
    #url(r'^(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT})
]

#handler404 = 'CMDB_Server.views.page_not_found'

CMDB/CMDB_Server/models.py
#!/usr/bin/env python
#-*-coding:utf-8-*-
from django.db import models
from django.contrib.auth.models import  User
# Create your models here.
class CmdbPermission(models.Model):
    name=models.CharField(max_length=32)
    url=models.CharField(max_length=32)
    request_method=models.CharField(max_length=32)
    request_args=models.CharField(max_length=64,null=True)
    request_args_value=models.CharField(max_length=32,null=True)
class UserPermission(models.Model):
     cmdbpermission=models.ForeignKey(CmdbPermission)
     user=models.ForeignKey(User)
class IDC(models.Model):
    idc_choices = ((1, u'广州奥飞IDC'),
                   (2, u'香港IDC'),
                   (3, u'深圳南山IDC'),
                   (4, u'深圳岗厦IDC'))
    name=models.SmallIntegerField(choices=idc_choices,verbose_name=u'IDC名称',default='GZ',null=True)
    location=models.CharField(u'IDC位置',max_length=128)
    contact_name=models.CharField(u'IDC联系人',max_length=32)
    contact_tel=models.CharField(u'联系人电话',max_length=32)
    create_date = models.DateTimeField(u'创建日期', blank=True, auto_now_add=True)
    update_date = models.DateTimeField(u'修改日期', blank=True, auto_now=True)
class Asset(models.Model):
    assetno = models.CharField(max_length=32)
    asset_type_choices = (
        ('server', u'服务器'),
        ('switch', u'交换机'),
        ('router', u'路由器'),
        ('firewall', u'防火墙'),
        ('storage', u'存储设备'),
        ('NLB', u'F5'),
        ('wireless', u'无线AP'),
        ('others', u'其它类'),
    )
    asset_type = models.CharField(u'资产类型',choices=asset_type_choices, max_length=64, default='server')
    sn = models.CharField(u'资产SN号', max_length=128)
    servermodel=models.CharField(u'资产型号',max_length=64)
    business_ip = models.GenericIPAddressField(u'管理IP', blank=True, null=True)
    #trade_date = models.DateField(u'购买时间', null=True, blank=True)
    expire_date = models.DateField(u'过保日期', null=True, blank=True)
    #price = models.FloatField(u'价格', null=True, blank=True)
    business_unit_choices=((1,'product'),
                           (2,'bete'),
                           (3,'cn|test'),
                           (4,'other'))
    business_unit = models.SmallIntegerField(u'生产环境',choices=business_unit_choices,default=1)
    tags = models.CharField(u'资产标记',blank=True, max_length=128)
    admin = models.ForeignKey(User, verbose_name=u'资产管理员', null=True, blank=True)
    idc = models.ForeignKey(IDC,verbose_name=u'IDC杋房', null=True, blank=True)
    idc_cabinet = models.CharField(u'机柜号',max_length=32)
    create_type_choices=((1,u'人工'),
                         (2,u'自动'))
    create_type=models.SmallIntegerField(choices=create_type_choices,verbose_name=u'数据方式',default=2)
    #marker= models.TextField(u'备注', null=True, blank=True)
    status_type_choices = ((1, u'在线'),
                           (2, u'下线'))
    asset_status=models.SmallIntegerField(choices=status_type_choices,verbose_name=u'状态',default=1)
    reason=models.CharField(max_length=128,null=True)
    release_date=models.DateField(null=True,max_length=32)
    create_date = models.DateTimeField(u'创建日期',blank=True, auto_now_add=True)
    update_date = models.DateTimeField(u'修改日期',blank=True, auto_now=True)

    class Meta:
        verbose_name = '资产总表'
        verbose_name_plural = "资产总表"

    def __unicode__(self):
        return 'asset:%s' % self.assetno

class Server(models.Model):
    asset=models.OneToOneField(Asset)
    #os_type=models.CharField(u'系统类型',max_length=32)
    osrelease=models.CharField(u'系统版本',max_length=64)
    bip = models.GenericIPAddressField(u'业务IP', max_length=64)
    rip = models.GenericIPAddressField(u'管理IP', max_length=64, default='0.0.0.0')
    uptime=models.CharField(u'运行时长',max_length=64)
    users=models.CharField(max_length=64)
    create_date = models.DateTimeField(u'创建日期',blank=True, auto_now_add=True)
    update_date = models.DateTimeField(u'修改日期',blank=True, auto_now=True)

class Cpu(models.Model):
    server=models.ForeignKey(Server)
    cpumodel = models.CharField(u'cpu型号',max_length=64)
    cpucount = models.SmallIntegerField(u'cpu个数')
    cpucorecount=models.SmallIntegerField(u'cpu核心数')
    create_date = models.DateTimeField(u'创建日期',blank=True, auto_now_add=True)
    update_date = models.DateTimeField(u'修改日期',blank=True, auto_now=True)

class Disk(models.Model):
    server = models.ForeignKey(Server)
    disktotalsize=models.CharField(u'磁盘大小',max_length=32)
    diskcount=models.SmallIntegerField(u'磁盘个数')
    diskraid=models.CharField(u'RAID',max_length=32)
    df=models.TextField(null=True)
    create_date = models.DateTimeField(u'创建日期',blank=True, auto_now_add=True)
    update_date = models.DateTimeField(u'修改日期',blank=True, auto_now=True)

class Memory(models.Model):
    server = models.ForeignKey(Server)
    memorycount=models.SmallIntegerField(u'内存个数')
    memorysizeper=models.CharField(u'单条内存大小',max_length=32)
    memorytotal=models.CharField(u'内存总大小',max_length=32)
    memory_slot_count = models.CharField(u'内存插槽个数',max_length=32)
    create_date = models.DateTimeField(u'创建日期',blank=True, auto_now_add=True)
    update_date = models.DateTimeField(u'修改日期',blank=True, auto_now=True)

class Services(models.Model):
    server = models.ForeignKey(Server)
    name=models.TextField(u'应用名称')
    crontab=models.TextField()

CMDB/templates/cmdb/asset.html
{% extends 'cmdb/index.html' %}
{% load customtags %}
{% block page-content %}
    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <ol class="breadcrumb page-breadcrumb pull-left h4">
            <li class=""><i class="fa fa-th-list"></i>&nbsp;<a href="index.html">资产列表</a></li>
        </ol>
    </div>
    <!--END TITLE & BREADCRUMB PAGE-->
    <!--BEGIN CONTENT-->
    <div class="page-content">
        <div class="panel panel-green">
            <div class="panel-heading">资产列表<span class="pull-right">
               {% if add_perm %}
                   <a href="/cmdb/edit?action=add" class="btn  btn-xs btn-blue" style="margin-right: -10px"><i class="fa fa-plus"></i>增加</a>
               {% endif %}
                {% if edit_perm %}
                    <a href="#"  class="btn  btn-xs  btn-grey" id="editbtn" onclick="return tablecheck();" data-container="body" data-toggle="popover" data-placement="top" data-content="Please select a row of data ." style="margin-right: -10px"><i class="fa fa-edit"></i>编辑</a>
                {% endif %}
                {% if del_perm %}
                    <a href="#"  id='delbtn' class="btn  btn-xs  btn-red" onclick="return tablecheck();" data-container="body" data-toggle="popover" data-placement="bottom" data-content="Please select a row of data ."><i class="fa fa-trash-o"></i>删除</a>
                {% endif %}<!--a href="#"  id='linebtn' class="btn  btn-xs btn-warning" onclick="return tablecheck();" data-container="body" data-toggle="popover" data-placement="bottom" data-content="Please select a row of data ."><i class="fa fa-sort"></i>上下线</a--></span></div>
            <div class="panel-body" style="padding:0px">
                <table class="table table-hover table-striped table-bordered  tb-sticky-header" style="margin-bottom: 0px">
                    <thead id="th">
                    <tr >
                        <th width="5%"><i class="fa fa-check-square-o" data-container="body" data-toggle="popover" data-placement="bottom" data-content="only select one"></i></th>
                        <th >ID</th>
                        <th >资产编号</th>
                        <th >资产类型</th>
                        <th >资产SN号</th>
                        <th >资产型号</th>
                        <th >业务IP</th>
                        <th >管理IP</th>
                        <th >生产环境</th>
                        <th >IDC杋房</th>
                        <th >机柜号</th>
                        <th>数据类型</th>
                        <th>状态</th>
                        <th >管理员</th>
                        <th>出厂日期</th>
                        <th>更新时间</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for asset in assetobj %}
                        <tr><td><input type="checkbox" /></td><td><a href="{% url 'detail' asset.id %}" data-hover="tooltip" title="open detail" style="color: #0e76a8">{{ asset.id }}</a></td><td>{{ asset.assetno }}</td><td>{{ asset.get_asset_type_display}}</td><td>{{ asset.sn }}</td><td>{{ asset.servermodel }}</td><td>{{ asset.business_ip }}</td><td>{{ asset.server.rip }}</td>
                            <td>{{ asset.get_business_unit_display }}</td><td>{{ asset.idc.name }}</td><td>{{ asset.idc_cabinet }}</td><td>{{ asset.get_create_type_display }}</td><td class="status{{asset.asset_status}}">{{ asset.get_asset_status_display}}</td><td>{{ asset.admin}}</td><td>{{ asset.release_date|date:"Y-m-d"}}</td><td>{{ asset.update_date|date:"Y-m-d H:i:s" }}</td></tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="pull-right" style="height:60px;margin-top: -10px">
                    <div id="table_id_paginate" class="dataTables_paginate paging_simple_numbers">
                        <ul class="pagination">
                            {% if assetobj.has_previous %}
                                <li id="table_id_previous" tabindex="0" aria-controls="table_id" class="paginate_button previous"><a href="?page={{ assetobj.previous_page_number }}">&laquo;</a></li>
                            {% endif %}
                            {% for page_num in assetobj.paginator.page_range %}
                                {% pageabs assetobj.number page_num %}
                            {% endfor %}
                            {% if assetobj.has_next %}
                                <li id="table_id_next" tabindex="0" aria-controls="table_id" class="paginate_button next"><a href="?page={{ assetobj.next_page_number }}">&raquo;</a></li>
                            {% endif %}
                        </ul></div></div>
            </div>
        </div>
    </div>
    <!--END CONTENT-->
{% endblock %}
{% block js %}
    <script type="text/javascript">
        function tablecheck() {
            checkyesorno=false
            checkednum=0
            $('table :checkbox').each(function () {
                        var tf = $(this).prop('checked');
                        if (tf){
                            var assetid=$(this).parent().parent().siblings().find('a').text()
                            $('#editbtn').attr('href',"{% url 'edit' %}?action=edit&id="+assetid)
                            $('#delbtn').attr('href',"{% url 'edit' %}?action=del&id="+assetid)
                            $('#linebtn').attr('href',"{% url 'edit' %}?action=line&id="+assetid)
                            checkyesorno=true
                            checkednum=checkednum+1
                        }
                    }
            )
            if (checkyesorno==false){
                return false;
            }
            if(checkednum>1){
                alert('只能选择一个')
                return false
            }
        }
    </script>
{% endblock %}

CMDB/templates/cmdb/detail.html
{% extends 'cmdb/index.html' %}
{% block page-content %}
    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">

        <ol class="breadcrumb page-breadcrumb pull-left h4">
            <li class="active"><a href='{% url 'asset' %}' class="fa  fa-arrow-circle-left"  data-hover="tooltip" title="返回" ></a>&nbsp;<span>{{ assetobj.assetno }}详细信息</span></li>
        </ol>

    </div>
    <!--END TITLE & BREADCRUMB PAGE-->
    <!--BEGIN CONTENT-->
    <div class="page-content">
        <div class="col-lg-12 detail">
            <div class="panel panel-grey">
                <div class="panel-heading">资产概述</div>
                <div class="panel-body" style="padding:0px">
                    <table class="table table-hover table-bordered">
                        <thead>
                        <tr>
                            <th >资产编号</th>
                            <th >资产类型</th>
                            <th >资产SN号</th>
                            <th >资产型号</th>
                            <th >业务IP</th>
                            <th >管理IP</th>
                            <th >生产环境</th>
                            <th >IDC杋房</th>
                            <th >机柜号</th>
                            <th>数据类型</th>
                            <th>状态</th>
                            <th >管理员</th>
                            <th>出厂日期</th>
                            <th >更新时间</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                        <tr><td>{{ assetobj.assetno }}</td><td>{{ assetobj.get_asset_type_display}}</td><td>{{ assetobj.sn }}</td><td>{{ assetobj.servermodel }}</td><td>{{ assetobj.business_ip }}</td><td>{{ assetobj.server.rip }}</td>
                            <td>{{ assetobj.get_business_unit_display }}</td><td>{{ assetobj.idc.name }}</td><td>{{ assetobj.idc_cabinet }}</td><td>{{ assetobj.get_create_type_display }}</td><td class="status{{assetobj.asset_status}}">{{ assetobj.get_asset_status_display}}</td><td>{{ assetobj.admin }}</td><td>{{ assetobj.release_date }}</td><td>{{ assetobj.update_date|date:"Y-m-d H:i:s" }}</td></tr>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            {% if assetobj.server%}
                <div >

                    <div class="panel panel-violet">
                        <div class="panel-heading">系统信息</div>
                        <div class="panel-body" style="padding:0px">
                            <table class="table table-hover table-bordered">
                                <thead>
                                <tr>
                                    <th>系统版本</th>
                                    <th>运行时长</th>
                                    <th >业务IP</th>
                                    <th >管理IP</th>
                                    <th>用户</th>
                                    <th>更新时间</th>
                                </tr>
                                </thead>
                                <tbody>

                                <tr>
                                    <td>{{ assetobj.server.osrelease }}</td>
                                    <td>{{ assetobj.server.uptime }}D</td>
                                    <td>{{ assetobj.server.bip }}</td>
                                    <td>{{ assetobj.server.rip }}</td>
                                    <td>{{ assetobj.server.users }}</td>
                                    <td>{{ assetobj.server.update_date|date:"Y-m-d H:i:s"  }}</td>
                                </tr>
                                {% for service in assetobj.server.services_set.select_related %}
                                    <tr><td >应用端口</td><td colspan="5"><pre class="pre-scrollable"  style="text-align: left;padding: 0px;background-color: inherit;border: none;max-height: 150px;margin: 0px">{{ service.name }}</pre></td></tr>
                                    <tr><td >定时任务</td><td colspan="5"><pre  style="text-align: left;padding: 0px;background-color: inherit;border: none;margin: 0px">{{ service.crontab }}</pre></td></tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="panel panel-yellow">
                        <div class="panel-heading">CPU信息</div>
                        <div class="panel-body" style="padding:0px">
                            <table class="table table-hover table-bordered">
                                <thead>
                                <tr>
                                    <th>Cpu型号</th>
                                    <th>Cpu逻辑个数</th>
                                    <th>Cpu总核数</th>
                                    <th>更新时间</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for cpu in assetobj.server.cpu_set.select_related %}
                                    <tr>
                                        <td>{{ cpu.cpumodel }}</td>
                                        <td>{{ cpu.cpucount }}</td>
                                        <td>{{ cpu.cpucorecount }}</td>
                                        <td>{{ cpu.update_date|date:"Y-m-d H:i:s"  }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="panel panel-green">
                        <div class="panel-heading">内存信息</div>
                        <div class="panel-body" style="padding:0px">
                            <table class="table table-hover table-bordered">
                                <thead>
                                <tr>
                                    <th>内存大小</th>
                                    <th>内存数量</th>
                                    <th>单条大小</th>
                                    <th>内存插槽数</th>
                                    <th>更新时间</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for memory in assetobj.server.memory_set.select_related %}
                                    <tr>
                                        <td>{{ memory.memorytotal }}</td>
                                        <td>{{ memory.memorycount }}</td>
                                        <td>{{ memory.memorysizeper }}</td>
                                        <td>{{ memory.memory_slot_count }}</td>
                                        <td>{{ memory.update_date|date:"Y-m-d H:i:s"  }}</td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="panel panel-blue">
                        <div class="panel-heading">硬盘信息</div>
                        <div class="panel-body" style="padding:0px">
                            <table class="table table-hover table-bordered">
                                <thead>
                                <tr>
                                    <th>硬盘大小</th>
                                    <th>硬盘数量</th>
                                    <th>RAID级别</th>
                                    <th>更新时间</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for disk in assetobj.server.disk_set.select_related %}
                                    <tr>
                                        <td>{{ disk.disktotalsize }}</td>
                                        <td>{{ disk.diskcount }}</td>
                                        <td>{{ disk.diskraid }}</td>
                                        <td>{{ disk.update_date|date:"Y-m-d H:i:s"  }}</td>
                                    </tr>
                                {% endfor %}
                                {% for disk in assetobj.server.disk_set.select_related %}
                                    {% if disk.df %}
                                        <tr>
                                            <td >分区信息</td><td colspan="3">
                                            <pre  style="text-align: left;padding: 0px;background-color: inherit;border: none;margin: 0px">{{ disk.df}}</pre></td></tr>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                </div>
            {% endif%}
    </div>
    <!--END CONTENT-->
{% endblock %}

CMDB/templates/cmdb/graph.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Hello Qunee</title>
    <link rel=stylesheet href=http://demo.qunee.com/editor/libs/bootstrap/css/bootstrap.css>
    <link rel=stylesheet href=http://demo.qunee.com/editor/libs/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css>
    <link rel=stylesheet href=http://demo.qunee.com/editor/libs/graph.editor/graph.editor.css>
</head>
<body class="layout">
<div id="editor" data-options="region:'center'"></div>
<script src="http://demo.qunee.com/editor/libs/js.js"></script>
<script src="http://demo.qunee.com/lib/qunee-min.js?v=1.8"></script>
<script src="http://demo.qunee.com/editor/libs/graph.editor/graph.editor.js"></script>
<script>
    $('#editor').graphEditor({callback: function(editor){
        var graph = editor.graph;
        var hello = graph.createNode("Hello", -100, -50);
        hello.image = Q.Graphs.server;
        var qunee = graph.createNode("Qunee", 100, 50);
        var edge = graph.createEdge("Hello\nQunee", hello, qunee);
        graph.moveToCenter();
    }});
</script>
</body>
</html>

CMDB/templates/cmdb/idc.html
{% extends 'cmdb/index.html' %}
{% block page-content %}
    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <ol class="breadcrumb page-breadcrumb pull-left h4">
            <li class=""><i class="fa fa-cubes"></i>&nbsp;<span>IDC信息</span></li>
        </ol>
    </div>
    <div class="page-content">
        <div class="col-lg-12 detail">
            <div class="panel panel-red">
                <div class="panel-heading">IDC信息</div>
                <div class="panel-body" style="padding:0px">
                    <table class="table table-hover table-bordered">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>名称</th>
                            <th>位置</th>
                            <th>联系人</th>
                            <th>联系方式</th>
                            <th>拓扑图</th>
                            <th>修改时间</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for idc in idcobj %}
                            <tr>
                                <td>{{ idc.id }}</td>
                                <td>{{ idc.name }}</td>
                                <td>{{ idc.location }}</td>
                                 <td>{{ idc.contact_name }}</td>
                                 <td>{{ idc.contact_tel }}</td>
                                <td><a href="{% url 'graph' %}" target="_blank"><span class="fa fa-map-marker"></span></a></td>
                                <td>{{ idc.update_date|date:"Y-m-d"  }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

CMDB/templates/cmdb/log.html
{% extends 'cmdb/index.html' %}

{% block page-content %}
    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <ol class="breadcrumb page-breadcrumb pull-left h4">
            <li class=""><i class="fa fa-file-text"></i><span>日志管理</span></li>
        </ol>
    </div>
    <div class="page-content">
    <textarea style="overflow: auto;width: 100%;height: 900px;" readonly="readonly" id="logtextarea">

    </textarea>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            $.get('/static/log.log',function (data) {
                $('#logtextarea').val(data);
                MsgScroll();
            });
            function MsgScroll(){
                $('#logtextarea').animate({
                    scrollTop:$('#logtextarea')[0].scrollHeight},800);
            }
        })
    </script>
{% endblock %}

CMDB/templates/cmdb/os.html
{% extends 'cmdb/index.html' %}

{% block page-content %}
    <div id="title-breadcrumb-option-demo" class="page-title-breadcrumb">
        <ol class="breadcrumb page-breadcrumb pull-left h4">
            <li class=""><i class="fa fa-cubes"></i>&nbsp;<span>资产信息</span></li>
        </ol>
    </div>
    <div class="page-content">
        <div class="col-lg-12 detail">
            <div class="panel panel-red">
                <div class="panel-heading">下线服务器信息</div>
                <div class="panel-body" style="padding:0px">
                    <table class="table table-hover table-bordered">
                        <thead>
                        <tr>
                            <th >资产编号</th>
                            <th >资产SN号</th>
                            <th >资产型号</th>
                            <th >管理IP</th>
                            <th >生产环境</th>
                            <th >IDC杋房</th>
                            <th>硬盘大小</th>
                            <th>硬盘数量</th>
                            <th >RAID</th>
                            <th>状态</th>
                            <th >修改日期</th>
                        </tr>
                        </thead>
                        <tbody>
                          {% for asset in assetobj %}
                            <tr>
                                <td>{{ asset.assetno }}</td>
                                <td>{{ asset.sn }}</td>
                                <td>{{ asset.servermodel }}</td>
                                 <td><a href="https://{{ asset.server.rip }}/login.html" target="_blank">{{ asset.server.rip}}</a></td>
                                 <td>{{ asset.get_business_unit_display }}</td>
                                <td>{{ asset.idc.name }}</td>
                                {% for disk in asset.server.disk_set.select_related %}
                                <td>{{ disk.disktotalsize}}</td>
                                 <td>{{ disk.diskcount  }}</td>
                                 <td>{{ disk.diskraid }}</td>
                                {% endfor %}
                               <td class="status{{ asset.asset_status }}">{{ asset.get_asset_status_display}}</td>
                                <td>{{ asset.update_date|date:"Y-m-d"  }}</td>
                            </tr>
                         {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}